steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/docker-repo/portfolio:latest',
      '--build-arg', 'NODE_VERSION=18',
      '.'
    ]
    env:
      - 'DOCKER_BUILDKIT=1'
  
  # Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/docker-repo/portfolio:latest']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'portfolio'
      - '--image'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/docker-repo/portfolio:latest'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'OPENAI_API_KEY=${_OPENAI_API_KEY}'

images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/docker-repo/portfolio:latest'

options:
  logging: CLOUD_LOGGING_ONLY 